package com.ptcm.resource;

public interface Language {
	public String MAIN_MANAGERMENT_TAB 							= "MAIN_MANAGERMENT_TAB";
	public String MAIN_MANAGERMENT_TAB_STATION 					= "MAIN_MANAGERMENT_TAB_STATION";
	public String MAIN_MANAGERMENT_TAB_STATION_CB_SELECTALL		= "MAIN_MANAGERMENT_TAB_STATION_CB_SELECTALL";
	public String MAIN_MANAGERMENT_TAB_STATION_BTN_EDIT			= "MAIN_MANAGERMENT_TAB_STATION_BTN_EDIT";
	public String MAIN_MANAGERMENT_TAB_STATION_BTN_SEARCH		= "MAIN_MANAGERMENT_TAB_STATION_BTN_SEARCH";

	public String MAIN_MANAGERMENT_TAB_STATION_ADDFRAME_TITLE	= "MAIN_MANAGERMENT_TAB_STATION_ADDFRAME_TITLE";

	public String MAIN_MANAGERMENT_TAB_STATION_BTN_ADDSTATION	= "MAIN_MANAGERMENT_TAB_STATION_BTN_ADDSTATION";
	public String MAIN_MANAGERMENT_TAB_STATION_BTN_DELETE		= "MAIN_MANAGERMENT_TAB_STATION_BTN_DELETE";


	public String MAIN_MANAGERMENT_TAB_CAR						= "MAIN_MANAGERMENT_TAB_CAR";
	public String MAIN_MANAGERMENT_TAB_CAR_CB_SELECTALL			= "MAIN_MANAGERMENT_TAB_CAR_CB_SELECTALL";
	public String MAIN_MANAGERMENT_TAB_CAR_BTN_EDIT				= "MAIN_MANAGERMENT_TAB_CAR_BTN_EDIT";
	public String MAIN_MANAGERMENT_TAB_CAR_BTN_DELETE			= "MAIN_MANAGERMENT_TAB_CAR_BTN_DELETE";
	public String MAIN_MANAGERMENT_TAB_CAR_BTN_SEARCH			= "MAIN_MANAGERMENT_TAB_CAR_BTN_SEARCH";
	public String MAIN_MANAGERMENT_TAB_CAR_BTN_ADDCAR			= "MAIN_MANAGERMENT_TAB_CAR_BTN_ADDCAR";
	public String MAIN_MANAGERMENT_TAB_CAR_ADDFRAME_TITLE		= "MAIN_MANAGERMENT_TAB_CAR_ADDFRAME_TITLE";

	public String MAIN_MANAGERMENT_TAB_DRIVER					= "MAIN_MANAGERMENT_TAB_DRIVER";
	public String MAIN_MANAGERMENT_TAB_DRIVER_CB_SELECTALL		= "MAIN_MANAGERMENT_TAB_CAR_CB_SELECTALL";
	public String MAIN_MANAGERMENT_TAB_DRIVER_BTN_EDIT			= "MAIN_MANAGERMENT_TAB_DRIVER_BTN_EDIT";
	public String MAIN_MANAGERMENT_TAB_DRIVER_BTN_DELETE		= "MAIN_MANAGERMENT_TAB_DRIVER_BTN_DELETE";
	public String MAIN_MANAGERMENT_TAB_DRIVER_BTN_SEARCH		= "MAIN_MANAGERMENT_TAB_DRIVER_BTN_SEARCH";
	public String MAIN_MANAGERMENT_TAB_DRIVER_BTN_ADDDRIVER		= "MAIN_MANAGERMENT_TAB_DRIVER_BTN_ADDDRIVER";
	public String MAIN_MANAGERMENT_TAB_DRIVER_ADDFRAME_TITLE	= "MAIN_MANAGERMENT_TAB_DRIVER_ADDFRAME_TITLE";
	
	public String MAIN_MANAGERMENT_TAB_OWNER					= "MAIN_MANAGERMENT_TAB_OWNER"; 
	


	public String MAIN_SCHEDULE_TAB								= "MAIN_SCHEDULE_TAB";
	public String MAIN_SCHEDULE_TAB_BTN_NOTIFY					= "MAIN_SCHEDULE_TAB_BTN_NOTIFY";
	public String MAIN_SCHEDULE_TAB_BTN_GENERRATESSCHEDULE		= "MAIN_SCHEDULE_TAB_BTN_GENERRATESSCHEDULE";
	public String MAIN_SCHEDULE_TAB_CB_BUS						= "MAIN_SCHEDULE_TAB_CB_BUS";
	public String MAIN_SCHEDULE_TAB_BTN_SEARCH					= "MAIN_SCHEDULE_TAB_BTN_SEARCH";

	public String MAIN_NOTIFY_TAB 								= "MAIN_NOTIFY_TAB";
	public String MAIN_NOTIFY_TAB_BT_BUS						= "MAIN_NOTIFY_TAB_BT_BUS";
	public String MAIN_BTN_SEARCH								= "MAIN_BTN_SEARCH";

}